@startuml Create Appointment (Post)

header Dentist Sequence Diagram
footer Page %page% of %lastpage%
title "Create Appointment (Post)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:appointments" as routerAppointments
participant "<<controllers>>\n:appointments" as controllersAppointments
participant "<<model>>\n:Appointment" as modelAppointment
database "<<MongoDB>>\n:appointments" as AppointmentsDatabase

client->server ++:req.get('/api/v1/appointments')
server->routerAppointments ++:app.use('/api/v1/appointments',appointments)
'alt successful case 
    routerAppointments -> controllersAppointments ++:addAppointment()
' else existedAppointments.length >= 1 
'     routerAppointments->client --:response
' end

alt successful case 
    controllersAppointments->modelAppointment ++:create(req.body)
else existedAppointments.length >= 1 
    controllersAppointments->client --:response
end
modelAppointment ->AppointmentsDatabase ++: AppointmentSchema
AppointmentsDatabase --> modelAppointment --: appointment
controllersAppointments <-- modelAppointment --:appointment
controllersAppointments->client --:response
@enduml

